//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuSatisOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public string Status { get; set; }
        public string price { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
